server:
  port: 8080
  error:
    include-message: always

spring:
    application:
        name: rag-chatbot

    profiles:
      active: local

    jpa:
      open-in-view: false
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 100

# AI Service 설정
ai-service:
  base-url: ${AI_SERVICE_BASE_URL:http://localhost:8000}
  api-key: ${AI_API_KEY:dev_api_key}
  timeout: 60000  # 60초

logging:
  level:
    com.sjpark: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
