spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: raguser
    password: ragpass123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 문서 저장 경로
file:
  upload:
    dir: D:/ai-chatbot-workspace/shared

# AI 서비스 설정
ai:
  service:
    url: http://127.0.0.1:8000  # FastAPI 서버 주소
    timeout: 30000               # 30초 타임아웃

# CORS 설정 (개발용)
cors:
  allowed-origins: http://localhost:3000,http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  exposed-headers: X-Session-ID