server:
  port: 8080

spring:
    application:
        name: rag-chatbot

    profiles:
      active: local

    web:
      resources:
        static-locations: classpath:/static/

logging:
  level:
    root: INFO
    com.sjpark.chatbot: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
