server:
  port: 8080

app:
  ai:
    base-url: http://127.0.0.1:8000  # FastAPI 엔드포인트
  file:
    upload-dir: D:/ai-chatbot-workspace/storage/data/uploaded # 파일 업로드 디렉토리

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true

  config:
    import: application-secret.yml
  
  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  data:
    redis:
      host: localhost
      port: 6379

